---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pinger-operator
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pinger-operator-role
rules:
  - apiGroups: ["example.com"]
    resources: ["pingers"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: ["example.com"]
    resources: ["pingers/status"]
    verbs: ["get", "update", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pinger-operator-rolebinding
subjects:
- kind: ServiceAccount
  name: pinger-operator
  namespace: default
roleRef:
  kind: ClusterRole
  name: pinger-operator-role
  apiGroup: rbac.authorization.k8s.io