apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: pingers.example.com
spec:
  group: example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                url:
                  type: string
            status:
              type: object
              properties:
                lastPing:
                  type: string
  scope: Namespaced
  names:
    plural: pingers
    singular: pinger
    kind: Pinger